#!/usr/local/bin/python
#!/usr/bin/env python
helpstr = '''
get_rfc_ptr v1.0.2
5/8/2017
This program retireves observed and forecast temperature and precip from the
NWRFC.

POC: Gunnar Leffler
     Nick Zhao

FORMATTING
==========

configuration file example
--------------------------
WWPI1:
  PP:
    observed: WWPI.Precip-Inc-Sensor2.Total.~1Day.1Day.RFC-RAW
  PP6:
    observed: WWPI.Precip-Inc.Total.~6Hours.6Hours.RFC-RAW
WYNI1:
  PC6:
    observed: WYNI.Precip-Cum.Inst.0.0.RFC-RAW
  PP6:
    observed: WYNI.Precip-Inc.Total.1Hour.1Hour.RFC-RAW
  TA:
    observed: WYNI.Temp-Air.Inst.0.0.RFC-RAW
  TN:
    observed: WYNI.Temp-Air.Min.~1Day.1Day.RFC-RAW
  TX:
    observed: WYNI.Temp-Air.Max.~1Day.1Day.RFC-RAW

Output
------
Output of this program is timeseries data in "instapost" YAML format

PARAMETERS
==========
'''

import sys, os, datetime, requests, re, random, argparse, json, yaml
from xml.dom import minidom

#--------------------------------------------------------------------------------
#Configuration
#--------------------------------------------------------------------------------

dataURL = "https://www.nwrfc.noaa.gov/weather/xml/"

PE_xref = {
    "TX": "temp_max",
    "TN": "temp_min",
    "TA": "temp_air",
    "PP": "precip_inc",
    "PC": "precip_cum"
}

prod_xref = {
      "forecast": {
          "PP": "qpf24",
          "PC": "qpf24",
          "PP6": "qpf6",
          "PC6": "qpf6",
          "TX": "qtf24max",
          "TA": "qtf24max",
          "TN": "qtf24min"
      },
      "observed": {
          "PP": "qpe6",
          "PC": "qpe6",
          "PP6": "qpe6",
          "PC6": "qpe6",
          "TX": "qte24max",
          "TA": "qte24max",
          "TN": "qte24min"
      }
  }

units_xref = {"TX": "F", "TN": "F", "TA": "F", "PP": "in", "PC": "in"}

WScache = {}


#--------------------------------------------------------------------------------
#XML to dictionary conversion
#--------------------------------------------------------------------------------
def parse_element(element):
  '''Converts XML to dictionary data structure
    '''
  dict_data = dict()
  if element.nodeType == element.TEXT_NODE:
    if element.data.strip() != "":
      dict_data = element.data
  if element.nodeType not in [
      element.TEXT_NODE, element.DOCUMENT_NODE, element.DOCUMENT_TYPE_NODE
  ]:
    for item in element.attributes.items():
      dict_data["@" + item[0]] = item[1]
  if element.nodeType not in [element.TEXT_NODE, element.DOCUMENT_TYPE_NODE]:
    for child in element.childNodes:
      child_name, child_dict = parse_element(child)
      if child_name in dict_data:
        if child_dict != {}:
          try:
            dict_data[child_name].append(child_dict)
          except AttributeError:
            dict_data[child_name] = [dict_data[child_name], child_dict]
      else:
        if child_dict != {}:
          dict_data[child_name] = child_dict
    if dict_data.keys() == ["#text"]:
      dict_data = dict_data["#text"]
  return element.nodeName, dict_data


def xml2dict(txt):
  dom = minidom.parseString(txt.encode('utf-8'))
  return parse_element(dom)[1]


def xml2json(txt):
  return json.dumps(xml2dict(txt), sort_keys=True, indent=1)


#--------------------------------------------------------------------------------
#Helper Methods
#--------------------------------------------------------------------------------


def loadConfig(path):
  if args.verbose:
    sys.stderr.write("loading config file...")
  output = yaml.safe_load(open(path))
  if args.verbose:
    sys.stderr.write(" %d entries found.\n" % (len(output)))
  return output


def getWebService(catalog):
  output = {}
  latest = {}
  for fname in catalog:
    product = fname.split("_")[0]
    if not product in latest: latest[product] = fname
    if fname > latest[product]: latest[product] = fname
  for product in latest:
    fname = latest[product]
    URL = dataURL + fname
    if args.verbose:
      sys.stderr.write("Getting %s \n" % (URL))
    try:
      raw = requests.get(URL).text
    except:
      raw = ""
      sys.stderr.write("could not retrieve %s " % (fname))
    try:
      t1 = xml2dict(raw)
      t1 = t1[t1.keys()[0]]
      t1 = t1[t1.keys()[0]]
      product = fname.split("_")[0]
      output[product] = {}
      for t in t1:
        output[product][t["@lid"]] = t
    except:
      sys.stderr.write("Could not parse %s" % (fname))
  return output


def parseWSdata(pe, wsPE, conf, loc, timefilter):

  def getTS(prod, loc):
    out = {
        "timeseries": {},
        "units": units_xref.get(pe[:2], "default"),
        "timezone": "GMT"
    }
    try:
      item = WScache[prod].get(loc, None)
      if not item:
        return out
      dh = item["@dh"]
      dc = item["@dc"]
      dt = datetime.datetime(
          int(dc[2:6]), int(dc[6:8]), int(dc[8:10]), int(dh[2:]))
      interval = datetime.timedelta(hours=6)
      indexer = "@per"
      if "day0" in item:
        interval = datetime.timedelta(hours=24)
        indexer = "@day"
      i = 0
      while i != -1:
        idx = indexer + str(i)
        if not idx in item:
          break
        try:
          out["timeseries"][dt.isoformat()] = float(item[idx])
        except:
          pass
        i += 1
        dt += interval
      if pe[:2] == "PC" or (prod == "qpe6" and pe == "PP"):
        dt -= interval
        out["timeseries"] = {dt.isoformat(): float(item.get("Total", 0))}
    except:
      sys.stderr.write("No Data Found for %s %s" % (loc, pe))
    return out

  output = {}
  if "forecast" in conf:
    if not isinstance(conf["forecast"], list):
      conf["forecast"] = [conf["forecast"]]
    for path in conf["forecast"]:
      prod = prod_xref["forecast"].get(pe, None)
      if prod:
        output[path] = getTS(prod, loc)
      else:
        sys.stderr.write("No Forecast Found %s %s \n" % (loc, pe))
  if "observed" in conf:
    if not isinstance(conf["observed"], list):
      conf["observed"] = [conf["observed"]]
    for path in conf["observed"]:
      prod = prod_xref["observed"].get(pe, None)
      if prod:
        output[path] = getTS(prod, loc)
      else:
        sys.stderr.write("No Observed Data Found %s %s \n" % (loc, pe))
  if "blended" in conf:
    if not isinstance(conf["blended"], list):
      conf["blended"] = [conf["blended"]]
    for path in conf["blended"]:
      prod = prod_xref["observed"].get(pe, None)
      if prod:
        output[path] = getTS(prod, loc)
      else:
        sys.stderr.write("No Observed Data Found %s %s \n" % (loc, pe))
      if "forecast" in conf:
        prod = prod_xref["forecast"].get(pe, None)
        if prod:
          output[path]["timeseries"].update(getTS(prod, loc)["timeseries"])
  return output


def makeconfig(critpath):
  crit = open(critpath, "r").readlines()
  leftovers = []
  for line in crit:
    tokens = line.split(";")[0].split("=")
    loc, pe, tse, duration = tokens[0][2:].split(".")
    if pe in PE_xref:
      if pe[0] == "T" and ".MIN." in tokens[1].upper():
        pe = "TN"
      elif pe[0] == "T" and ".MAX." in tokens[1].upper():
        pe = "TX"
      if pe[0] == "P" and not "DAY" in tokens[1].upper():
        pe += '6'
      if not loc in config:
        config[loc] = {}
      if not pe in config[loc]:
        config[loc][pe] = {}
      if tse[0] == "F":
        config[loc][pe]["forecast"] = tokens[1]
      else:
        config[loc][pe]["observed"] = tokens[1]
      if "forecast" in config[loc][pe] and "observed" in config[loc][pe]:
        parts = config[loc][pe]["observed"].split(".")
        parts[-1] = "BLEND-RFC-OBS-RFC-FCST"
        config[loc][pe]["blended"] = ".".join(parts).replace(
            ".1Day.1", ".~1Day.1").replace(".6Hours.6", ".~6Hours.6")
    else:
      leftovers.append(line)
  print yaml.safe_dump(config, default_flow_style=False)
  print "---"
  print "".join(leftovers)


def getCatalog():
  path = ""
  catalog = []
  if args.verbose:
    sys.stderr.write("Getting catalog file from server...\n")
  today = datetime.datetime.now().strftime('%Y%m%d')
  cat_url = 'https://www.nwrfc.noaa.gov/misc/downloads/downloads.php'
  payload = {'filter': '', 'sortasc': 'true', 'sortby': 'date'}
  for typ in ['precipitation', 'temperature']:
    for kind in ['observed', 'forecast']:
      payload['type'] = dtype = '%s_%s_points' % (kind, typ)
      r = requests.get(cat_url, params=payload)
      if args.verbose:
        sys.stderr.write(dtype + "\n")
        sys.stderr.write(r.url + "\n")
      data = json.loads(r.text)
      for row in data:
        if 'fn' in row:
          catalog.append(row['fn'])

  return catalog


#--------------------------------------------------------------------------------
# main()
#--------------------------------------------------------------------------------
catalog = {}
args = {}
config = {}
if __name__ == "__main__":
  p = argparse.ArgumentParser(
      description=helpstr, formatter_class=argparse.RawDescriptionHelpFormatter)
  p.add_argument('config', help='YAML formatted Configuration file')
  p.add_argument('-l', '--lookback', help='Lookback a number of days')
  p.add_argument('-v', '--verbose', action='store_true', help='Work verbosely')
  p.add_argument(
      '-rx', '--rawXML', action='store_true', help='Output raw XML from RFC')
  p.add_argument(
      '-rj', '--rawJSON', action='store_true', help='Output JSON from RFC')
  p.add_argument(
      '-m',
      '--makeconfig',
      action='store_true',
      help='Makes a config file from the specified crit file')
  p.add_argument(
      '-c', '--catalog', action='store_true', help='Output catalog from RFC')
  args = p.parse_args()

  if args.makeconfig:
    makeconfig(args.config)
    sys.exit(0)

  catalog = getCatalog()
  if args.catalog:
    print json.dumps(catalog, sort_keys=True, indent=2)
    sys.exit()

  WScache = getWebService(catalog)
  config = loadConfig(args.config)
  if args.lookback:
    lookback = args.lookback
  else:
    lookback = '5'
  output = {}
  for loc in config:
    if config[loc] == None:
      sys.stderr.write("Error, nothing defined for %s." % loc)
      continue
    for pe in config[loc]:
      timefilter = config[loc][pe].get("timefilter", "")
      wsPE = config[loc][pe].get(
          "use_pe", pe)  #sometimes the RFC misfiles data under other PEs
      output = parseWSdata(pe, wsPE, config[loc][pe], loc, timefilter)
      if not args.rawXML and not args.rawJSON and output != {}:
        print yaml.safe_dump(output, default_flow_style=False)
        print "---"

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
