1A03P Barkerville:
  PC: BKVB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: BKVB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: BKVB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: BKVB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: BKVB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: BKVB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
1C12P Green Mountain:
  PC: GRNB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: GRNB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: GRNB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: GRNB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: GRNB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: GRNB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
1F03P Park Mountain:
  PC: PKMB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: PKMB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: PKMB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: PKMB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: PKMB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: PKMB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2A06P Mount Revelstoke:
  PC: MTRB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: MTRB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: MTRB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: MTRB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: MTRB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: MTRB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2A21P Molson Creek:
  PC: MOLB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: MOLB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: MOLB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: MOLB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: MOLB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: MOLB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2B06P Barnes Creek:
  PC: BARB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: BARB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: BARB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: BARB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: BARB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: BARB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2C09Q Morrissey Ridge:
  PC: MORB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: MORB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: MORB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: MORB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: MORB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: MORB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2C10P Moyie Mountain:
  PC: MYMB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: MYMB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: MYMB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: MYMB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: MYMB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: MYMB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2C14P Floe Lake:
  PC: FLKB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: FLKB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: FLKB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: FLKB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: FLKB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: FLKB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2D08P East Creek:
  PC: EACB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: EACB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: EACB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: EACB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: EACB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: EACB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2F05P Mission Creek:
  PC: MCNB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: MCNB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: MCNB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: MCNB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: MCNB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: MCNB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2F18P Brenda Mines:
  PC: BMNB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: BMNB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: BMNB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: BMNB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: BMNB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: BMNB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
2G03P Blackwall Peak:
  PC: BLKB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: BLKB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: BLKB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: BLKB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: BLKB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: BLKB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
4A09P Pulpit Lake:
  PC: PPLB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: PPLB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: PPLB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: PPLB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: PPLB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: PPLB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
4A30P Aiken Lake:
  PC: AKNB.Precip-Cum.Inst.0.0.BCRFC-RAW
  SD: AKNB.Depth-Snow.Inst.0.0.BCRFC-RAW
  SW: AKNB.Depth-SWE.Inst.0.0.BCRFC-RAW
  TA: AKNB.Temp-Air.Inst.0.0.BCRFC-RAW
  TN: AKNB.Temp-Air.Min.~1Day.1Day.BCRFC-RAW
  TX: AKNB.Temp-Air.Max.~1Day.1Day.BCRFC-RAW
